---
dist: bionic
language: python
services: docker

env:
  global:
    - ROLE_NAME: cadvisor
  matrix:
    - MOLECULE_DISTRO: ubuntu2004

install:
  # Install test dependencies.
  - pip install molecule[docker] yamllint ansible-lint docker ansible==2.11

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
