---
# tasks file for cadvisor
- name: Start docker cadvisor container
  community.docker.docker_compose:
    state: present
    project_name: cadvisor
    definition:
      version: '2'
      services:
        cadvisor:
          image: "{{ cadvisor_image }}"
          container_name: "{{ cadvisor_container_name }}"
          ports:
            - "127.0.0.1:{{ cadvisor_host_port }}:9100"
          volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
          hostname: "{{ ansible_host }}"
          restart: always
      networks:
        default:
          external:
            name: "{{ cadvisor_docker_network_name }}"
