---
- name: Include docker-related tasks
  include_tasks: run_in_docker_container.yml
  when: cadvisor_run_in_docker

- name: Include standalone tasks
  include_tasks: run_standalone.yml
  when: not cadvisor_run_in_docker
