---
# tasks file for cadvisor
- name: Start docker cadvisor container
  become: yes
  become_user: root
  community.docker.docker_compose_v2:
    state: present
    project_name: cadvisor
    definition:
      services:
        cadvisor:
          image: "{{ cadvisor_image }}"
          container_name: "{{ cadvisor_container_name }}"
          command: "{{ cadvisor_additional_cmd_args }}"
          ports:
            - "{{ cadvisor_host_port }}:8080"
          volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
          hostname: "{{ ansible_host }}"
          restart: always
      networks:
        default:
          external: true
          name: "{{ cadvisor_docker_network_name }}"
  when: cadvisor_swarm_manager is undefined

- name: Deploy cadvisor_exporter to docker swarm
  block:
    - name: Ensure pip installation
      package:
        name: "python3-pip"
        state: present

    - name: Install newer version of pip itself
      pip:
        name: "pip"
        state: latest
        executable: pip3
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version != 24

    - name: Install jsondiff from pip
      pip:
        name: "jsondiff"
        state: present
        executable: pip3
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version != 24

    - name: Ensure jsondiff
      package:
        name: "python3-jsondiff"
        state: present
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version == 24

    - name: Deploy docker cadvisor_exporter container in swarm
      community.docker.docker_stack:
        state: present
        name: "{{ cadvisor_exporter_stack_name }}"
        with_registry_auth: yes
        compose:
          - version: '3.5'
            services:
              cadvisor:
                image: "{{ cadvisor_image }}"
                command: "{{ cadvisor_additional_cmd_args }}"
                hostname: "{{ cadvisor_container_name }}"
                labels: "{{ cadvisor_exporter_docker_labels }}"
                ports:
                  - "{{ cadvisor_host_port }}:8080"
                volumes:
                  - /:/rootfs:ro
                  - /var/run:/var/run:ro
                  - /sys:/sys:ro
                  - /var/lib/docker/:/var/lib/docker:ro
                  - /dev/disk/:/dev/disk:ro
                deploy: "{{ cadvisor_exporter_swarm_deploy }}"
            networks:
              default:
                name: "{{ cadvisor_docker_network_name }}"
                external: true
      run_once: True
  delegate_to: "{{ cadvisor_swarm_manager }}"
  when: cadvisor_swarm_manager is defined
